### ISSUE TITLE
add DocToolChain as git submodule

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#216]
to facilitate documentation

**Comment by rdmueller** [comment]
just did a diff with the old docs:
- content of the new branch is the same, but as the current HSC repo uses newer versions of Asciidoctor and HSC, they differ a bit:
- folder structure is a bit different. I guess this is not a problem since it seems to me that currently the docs are copied manually over to the gh-pages-branch, aren't they?
- docToolchain still uses the last stable HSC version and thus has less checks than the current HSC repo, but docToolchain will soon upgrade
- the asciidoc rendereing has some subtle differences. I will upgrade docToolchain to a newer asciidoctor version, as soon as there is some time for this.

So, currently, I would say that this is ready for a first PR...

**Comment by rdmueller** [comment]
next step will be to activate and configure some additional docToolchain features

**Comment by rdmueller** [comment]
move integration complexity (test.enabled=false) to docToolchain

**Comment by gernotstarke** [comment]
done, isn't it?
